version: '3.9'
services:
  server:
    build:
      context: ./server
    environment:
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET=${JWT_SECRET:-dev_secret_change_me}
    ports:
      - "4000:4000"
  client:
    build:
      context: ./client
      args:
        - VITE_API_URL=http://localhost:4000
    environment:
      - VITE_API_URL=http://localhost:4000
    ports:
      - "80"
    depends_on:
      - server


